#!/usr/bin/with-contenv sh
USER_HOME=/home/${USER_NAME}
# This file automaticalliy generated by /Users/schreepc/PycharmProjects/helxplatform/cloudtop-sdk/src/cloudtop_sdk/cli.py on Wed Nov  3 17:14:49 2021   

if [ ! -f $USER_HOME/Desktop/napari.desktop ] ; then
  if [ ! -d $USER_HOME/Desktop ] ; then
      mkdir $USER_HOME/Desktop
   fi
   cp /headless/Desktop/napari.desktop $USER_HOME/Desktop/napari.desktop
   chown -R $USER_NAME:$USER_NAME $USER_HOME/Desktop
fi

