#!/usr/bin/with-contenv sh
USER_HOME=/home/${USER_NAME}
# This file automaticalliy generated by /Users/schreepc/PycharmProjects/helxplatform/cloudtop-sdk/src/cloudtop_sdk/cli.py on Wed Nov  3 17:13:23 2021   

if [ ! -f $USER_HOME/Desktop/kstars.desktop ] ; then
  if [ ! -d $USER_HOME/Desktop ] ; then
      mkdir $USER_HOME/Desktop
   fi
   cp /headless/Desktop/kstars.desktop $USER_HOME/Desktop/kstars.desktop
   chown -R $USER_NAME:$USER_NAME $USER_HOME/Desktop
fi

if [ ! -f $USER_HOME/Desktop/ds9.desktop ] ; then
  if [ ! -d $USER_HOME/Desktop ] ; then
      mkdir $USER_HOME/Desktop
   fi
   cp /headless/Desktop/ds9.desktop $USER_HOME/Desktop/ds9.desktop
   chown -R $USER_NAME:$USER_NAME $USER_HOME/Desktop
fi

