pipeline {
  agent {
    kubernetes {
      label  'kaniko-agent'
      yaml '''
        apiVersion: v1
        kind: Pod
        metadata:
          name: kaniko-agent
        spec:
          containers:
          - name: jnlp
            volumeMounts:
            - name: workspace
              mountPath: /home/jenkins/agent
          - name: kaniko
            command:
            - /busybox/cat
            image: gcr.io/kaniko-project/executor:debug
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 1
                ephemeral-storage: "1G"
                memory: 4G
              limits:
                cpu: 1
                ephemeral-storage: "10G"
                memory: 16G
            tty: true
            volumeMounts:
            - name: jenkins-cfg
              mountPath: /kaniko/.docker
            - name: workspace
              mountPath: /home/jenkins/agent
          - name: tools
            command:
            - /bin/cat
            image: wateim/jenkins-tools:latest
            imagePullPolicy: Always
            tty: true
            volumeMounts:
            - name: workspace
              mountPath: /home/jenkins/agent
          - name: crane
            workingDir: /tmp/jenkins
            image: gcr.io/go-containerregistry/crane:debug
            imagePullPolicy: Always
            command:
            - /busybox/cat
            tty: true
          initContainers:
          - name: init
            image: busybox:1.28
            command: ['chmod', '777', '/workspace']
            volumeMounts:
            - name: workspace
              mountPath: /workspace
          volumes:
           - name: jenkins-cfg
             projected:
               sources:
               - secret:
                   name: rencibuild-imagepull-secret
                   items:
                   - key: .dockerconfigjson
                     path: config.json
           - name: workspace
             ephemeral:
               volumeClaimTemplate:
                 spec:
                   accessModes: [ "ReadWriteOnce" ]
                   storageClassName: nvme-ephemeral
                   resources:
                     requests:
                       storage: 7G
      '''
    }
  }
  environment {
    PATH = "/busybox:/kaniko:/ko-app/:$PATH"
    DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
    REGISTRY = "${env.DOCKER_REGISTRY}"
    REG_OWNER="helxplatform"
    REG_APP="cloudtop-image-analyses"
    COMMIT_HASH="${sh(script:"git rev-parse --short HEAD", returnStdout: true).trim()}"
    IMAGE_NAME="${REG_OWNER}/${REG_APP}"
    TAG1="$BRANCH_NAME"
    TAG2="$COMMIT_HASH"
  }
  stages {
    stage('Build') {
      steps {
        container(name: 'tools', shell: '/bin/sh') {
          sh '''
	  echo "Build stage"
          echo "Tools step"
          cd apps/image-analyses
          python ../../CloudTopBuilder.py image-analyses.yml helxplatform/cloudtop:$BRANCH_NAME
          '''
        }
        container(name: 'kaniko', shell: '/busybox/sh') {
          sh '''
          echo "Build step"
          cd apps/image-analyses
          /kaniko/executor --dockerfile Docker.image-analyses \
                           --context . \
                           --verbosity debug \
                           --no-push \
                           --destination $IMAGE_NAME:$TAG1 \
                           --destination $IMAGE_NAME:$TAG2 \
                           --tarPath image.tar
          '''
        }
      }
      post {
        always {
          archiveArtifacts artifacts: 'apps/image-analyses/image.tar', onlyIfSuccessful: true
        }
      }
    }
    stage('Test') {
      steps {
          sh '''
          echo "Stage test"
          '''
      }
    }
    stage('Publish') {
      steps {
        container(name: 'crane', shell: '/busybox/sh') {
          sh '''
          echo "Publish stage"
          echo "$DOCKERHUB_CREDS_PSW" | crane auth login -u $DOCKERHUB_CREDS_USR --password-stdin $REGISTRY
          crane push image.tar $IMAGE_NAME:$TAG1
          crane push image.tar $IMAGE_NAME:$TAG2
          '''
        }
      }
      post {
        cleanup {
          sh '''
          echo "Remove archived artifacts."
          '''
        }
      }
    }
  }
}

//  stages {
//      stage('Build') {
//          environment {
//              DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
//              DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
//          }
//          steps {
//              container('agent-docker') {
//                  sh '''
//                  echo build
//                  cd apps/image-analyses
//                  ../../CloudTopBuilder.py image-analyses.yml helxplatform/cloudtop:$BRANCH_NAME
//                  docker build -t helxplatform/cloudtop-image-analyses:$BRANCH_NAME -f Docker.image-analyses .
//                  '''
//              }
//          }
//      }
//      stage('Test') {
//          steps {
//              container('agent-docker') {
//                  sh '''
//                  echo test
//                  '''
//              }
//          }
//      }
//      stage('Publish') {
//          environment {
//              DOCKERHUB_CREDS = credentials("${env.REGISTRY_CREDS_ID_STR}")
//              DOCKER_REGISTRY = "${env.DOCKER_REGISTRY}"
//          }
//          steps {
//              container('agent-docker') {
//                  sh '''
//                  echo publish
//                  echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin $DOCKER_REGISTRY
//                  docker push helxplatform/cloudtop-image-analyses:$BRANCH_NAME
//                  '''
//              }
//          }
//      }
//  }
//}
