#!/usr/bin/with-contenv sh
USER_HOME=/home/${USER_NAME}
# This file automaticalliy generated by /Users/schreepc/PycharmProjects/helxplatform/cloudtop-sdk/src/cloudtop_sdk/cli.py on Thu Nov  4 11:16:14 2021   

if [ ! -f $USER_HOME/Desktop/gnu-octave.desktop ] ; then
  if [ ! -d $USER_HOME/Desktop ] ; then
      mkdir $USER_HOME/Desktop
   fi
   cp /headless/Desktop/gnu-octave.desktop $USER_HOME/Desktop/gnu-octave.desktop
   chown -R $USER_NAME:$USER_NAME $USER_HOME/Desktop
fi

